//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Weather
    {
        public int WeatherID { get; set; }
        public int LocationID { get; set; }
        public System.DateTime Date { get; set; }
        public string WeatherIcon { get; set; }
        public decimal Degree { get; set; }
    
        public virtual Location Location { get; set; }
    }
}
